max_jobs: 1

#image: Visual Studio 2017

#environment:
 # matrix:
  #- SQL_INSTANCE_NAME: SQL2016

test_script:
- ps: $ErrorActionPreference = "Stop"

#- ps: if (test-path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community") { $env:SQL_INSTANCE_NAME = 'SQL2016' }
#- ps: if (test-path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community") { $env:SQL_INSTANCE_NAME = 'SQL2017' }
#- ps: if (test-path "C:\Program Files\Microsoft Visual Studio\2022\Community") { $env:SQL_INSTANCE_NAME = 'SQL2019' }

- 'echo Starting SQL Server instance: %SQL_INSTANCE_NAME%'
- ps: Start-Service "MSSQL`$$env:SQL_INSTANCE_NAME"
- ps: Get-Service "MSSQL`$$env:SQL_INSTANCE_NAME" | fl *
- sqlcmd -S localhost -U SA -P Password12! -Q "select @@VERSION"

- ps: whoami
- ps: dir c:\projects
- icacls c:\projects
- icacls %appveyor_build_folder%

- echo Testing connectivity with named instance over named pipes
- ps: $env:connection_string_with_instance = "Server=(local)\$env:SQL_INSTANCE_NAME;Database=master;User ID=sa;Password=Password12!"
- ps: |
      $conn = New-Object System.Data.SqlClient.SqlConnection
      $conn.ConnectionString = $env:connection_string_with_instance
      $conn.Open()
      
      Write-Host "Creating Northwind database"
      $cmd = New-Object System.Data.SqlClient.SqlCommand("Create database Northwind", $conn)
      $cmd.ExecuteNonQuery() | Out-Null
      
      Write-Host "Restoring Northwind database"
      $cmd = New-Object System.Data.SqlClient.SqlCommand("Restore database Northwind from disk='$env:appveyor_build_folder\northwind.bak' WITH REPLACE, move 'Northwind' to '$env:appveyor_build_folder\northwind.mdf', move 'Northwind_log' to '$env:appveyor_build_folder\northwind_log.ldf'", $conn)
      $cmd.ExecuteNonQuery() | Out-Null
      
      Write-Host "List tables in Northwind database"
      $cmd = New-Object System.Data.SqlClient.SqlCommand("SELECT * FROM northwind.information_schema.tables", $conn)
      $reader = $cmd.ExecuteReader()
      while($reader.Read())
      {
        Write-Host "Table: $($reader["table_name"])"
      }
      $conn.Close()

- dir

build: off
